### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by frank-mendez** [frank-mendez/movie-browser#18]
**Describe the bug**
Currently on the favicon of the app it still using the vite favicon

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abhishekpaturkar** [comment]
I would like to help

**Comment by frank-mendez** [comment]
Hi @abhishekpaturkar sure, I will assign this to you.

**Comment by abhishekpaturkar** [comment]
The Husky test case are failing. Even without any file change

**Comment by nitverse** [comment]
Hey @frank-mendez can you provide me the icon?

**Comment by frank-mendez** [comment]
> The Husky test case are failing. Even without any file change

Hi @abhishekpaturkar can you send me the details of the failed husky. I will check it out. Thanks

**Comment by frank-mendez** [comment]
> Hey @frank-mendez can you provide me the icon? I have fixed it. here's the screenshot:
> 
> ![image](https://private-user-images.githubusercontent.com/88576631/355445593-279ac0a5-42d6-43f6-a947-599596c00d7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTIwNDEsIm5iZiI6MTcyMjk1MTc0MSwicGF0aCI6Ii84ODU3NjYzMS8zNTU0NDU1OTMtMjc5YWMwYTUtNDJkNi00M2Y2LWE5NDctNTk5NTk2YzAwZDdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDEzNDIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMGVlOTRlNGViNDgwODViNmYxYTI2YmY2YWQyNTBlOTc2OGFlOTQ2MWMzM2NmMzc3ZWQxOWZjNTU0YTFlZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lGlyE0HXmAfM9rwvhp3HoMGkqv_Wwn84xtxBayp_aGg)
We can use this icon
![favicon](https://github.com/user-attachments/assets/eb11eb47-31d0-4f3b-b5a7-0af8d9f10983)

**Comment by abhishekpaturkar** [comment]
I am able to change the icon but the test cases are failing
![Capture](https://github.com/user-attachments/assets/0d00c0dc-5142-4ec8-80ca-acd6afd17cc5)

**Comment by frank-mendez** [comment]
Mhmmm that is weird. Can you try to do a PR? The test is fine on my end.
![image](https://github.com/user-attachments/assets/d22be608-401f-4a05-8206-2fef39f862be)

**Comment by abhishekpaturkar** [comment]
I changes the icon
![Capture](https://github.com/user-attachments/assets/2030f161-45c4-437d-b74a-80d71c2e202b)
